### ISSUE TITLE
New Feature: Poder acceder a las secciones de la url como variables

### ISSUE THREAD

**Issue by agraciakuvut** [buuum/Route#1]
Ejemplo:

$route->get('/{url:proteccion-de-datos}/', ['App\Controller\Web\Pagina', 'getProteccionDatos'])->setName('proteccion-de-datos');

**Comment by buuum** [comment]
Esto ya funciona así. Pruébalo.

**Comment by buuum** [comment]
al llamar a getUrlRequest('proteccion-de-datos') no se tenga que especificar la url

**Comment by buuum** [comment]
it works from the version v1.0.17
